server:
  port: 8080

spring:
  application:
    name: slot-lab
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      show-values: always

keep-alive:
  interval-seconds: 840
  initial-delay-seconds: 15

history:
  session-ttl-days: 7
